### ISSUE TITLE
Seperate group select resets on marking

### ISSUE THREAD

**Issue by Alcb4** [fernandooliveira/moodle-block_marking_manager#26]
Hi,

In the Marking Manager, I select a group, after grading and saving, the 2nd time I click 'save', the group selection goes back to 'All Participants'

I'm using 
Moodle 3.0.5+ (Build: 20160721)
NED Marking manager Version: 2016090600

Thanks
Al

**Comment by fernandooliveira** [comment]
Hi Al,
This has been fixed please update to latest plugin code (3.1.1)

**Comment by Alcb4** [comment]
thanks for the quick reply, I updated to 3.1.2 (2016091500) but I'm afraid my problem still exists. 
Let me know if you want screenshots to see what happens 


On a side note I've just seen your call for testers, if you ever need these in the future I'll be here :)

**Comment by fernandooliveira** [comment]
Hello Al,  This issue has been fixed. Could you please download latest code and test?

**Comment by Alcb4** [comment]
Hi Fernando, I've just upgraded and it's all good here, many thanks!
Al
